### ISSUE TITLE
The Ocsimiragen battle plan.

### ISSUE THREAD

**Issue by Drup** [ocsigen/ocsigenserver#54]
Several people have expressed desire to help on this one, and web server internals are not really my forte, so every help is appreciated! 

As I see it, here is what remains to do. I will break each task by subtasks.
- [ ] Merge the [cohttp branch](https://github.com/ocsigen/ocsigenserver/compare/3.0.0-cohttp)
  - [x] First merge the non-cohttp parts of the branch, that means
    - [x] Numerous documentation improvements
    - [x] safe-string patches
    - [x] New interfaces that are not directly cohttp-related
  - [x] Rebase, update to lastest versions of cohttp and clean up the commit log
  - [ ] Review carefully (I'm counting on you for this part!) 
    - [ ] Ensure that all configuration are still available and remove the one that aren't.
    - [ ] Check that reverseproxy behaves as expected, in particular wrt to answer ordering. May be related to the `awake` parameter in https://github.com/ocsigen/ocsigenserver/pull/43.
- [ ] Replace pcre by re.
  - [ ] Add functions to re if they are missing, but I think @rgrinberg and @c-cube covered that.
  - [ ] According to @balat, it's very important not to change regexp's syntax is config files, need to take care of that.
- [ ] Implement a new Ocsipersist backend.
- [x] Remove what's left of ocamlnet.
- [ ] Celebrate by spawning lots of elioms on little ARM devices.

I think that's all. 

Some interfaces in the cohttp were merged as part of other PRs and the smaller the final patchset, the easier it will be to review and spot issues. I will try to work on merging the non-cohttp stuff.

cc @avsm @dinosaure @rgrinberg @vbmithr @balat @vouillon

**Comment by vouillon** [comment]
I have rebased the cohttp branch (new branch "cohttp").

**Comment by qrntz** [comment]
Is this still going?

**Comment by Drup** [comment]
Partially. The work on the cohttp branch was stalled, partially because I'm not working on it anymore, partially because the it is actually quite difficult ...

We haven't given up on the whole thing, though. :)

**Comment by qrntz** [comment]
@Drup, sorry; I've deleted my comment because I found yours at https://github.com/mirage/mirage/issues/569#issuecomment-235600500 :-)

Didn't expect you to answer so quickly.
